server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/api/main/**
        - id: scrim-service
          uri: lb://scrim-service
          predicates:
            - Path=/api/scrim/**
        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/api/team/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
