server:
  port: 8080
  error:
    include-message: always

spring:
  profiles:
    active: api
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/api/files/**, /api/games/**, /api/gamer-profiles/**, /testing/**
        - id: scrim-service
          uri: lb://scrim-service
          predicates:
            - Path=/api/scrims/**
        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/api/teams/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: tournament-service
          uri: lb://tournament-service
          predicates:
            - Path=/api/tournaments/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: ranking-service
          uri: lb://ranking-service
          predicates:
            - Path=/api/ranking/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
